server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/keystore.p12
    key-store-password: Piv0tal!22
    enabled: true
  port: 8443

logging:
  level:
    ROOT: info
    com.pksheldon4.webhooks:
      mutatingadmission: info
      imagepolicy: warn
      validatingadmission: warn